android_app_type:
  default: pwa
  type: enum
  choices:
    - app
  description: "Choose the app type you want to promote. Select pwa if you want to promote the site PWA version (works on Chrome) and select app if you have a published one in any store e.g. (Google Play) and you want to redirect users to the store app page."
android_appstore_link:
  type: string
  default: ""
  description: "Store link of your android app. This only activates if you choose 'app' app_type. E.g. https://play.google.com/store/apps/details?id=com.discourse"
ios_app:
  type: bool
  default: false
  description: "Select it if you want to promote your iOS app if you have a published one in (App Store) and you want to redirect users to the store app page."
apple_appstore_link:
  type: string
  default: ""
  description: "Store link of your iOS app. This only activates if you enabled the ios_app setting. E.g. https://apps.apple.com/us/app/discourse-hub/id1173672076"
app_logo_img:
  type: upload
  default: ""
  description: "Upload an image logo of your app."
app_cookie_lifespan:
  type: enum
  default: month
  choices:
    - none
    - minute
    - day
    - week
    - month
  description: "Choose the cookie expiration date. This cookie will be placed when user click the Continue button."
app_cookie_name:
  type: string
  default: "appModalClosed"
  description: ""
